### ISSUE TITLE
Old boinc account file causes the updated one to be ignored

### ISSUE THREAD

**Issue by ptrm** [balenalabs/rosetta-at-home#34]
The new `account_boinc.bakerlab.org_rosetta.xml` introduced in #24 is ignored by boinc due to the old `account_boinc.rosetta.bakerlab.org.xml` persisting on the boinc volume:
![Screenshot from 2020-04-29 09-09-08](https://user-images.githubusercontent.com/366258/80570529-3b207180-89fb-11ea-8f03-a854890674d2.png)

This might have lower impact on foldforcovid.io devices for the time being, but account change attempts won't succeed until the old account file is deleted.

**Comment by chrisys** [comment]
@ptrm it looks like this would only be an issue for those devices where the branch in #24 was deployed before it was merged? Since we renamed the file and added persistent storage in the same PR, it wouldn't be an issue for anyone following `master`, would it? Forgive me if I'm missing something here!

**Comment by ptrm** [comment]
Oh, that's right :D Closing then.
