### ISSUE TITLE
Have 2 or 3 task on Raspberry Pi 4 with 2GB

### ISSUE THREAD

**Issue by manuti** [balenalabs/rosetta-at-home#37]
Hey, after this change in #25 my **RPi4 2GB RAM** goes well and never run out of task, but I think this board can **manage 2 or 3 task simultaneously**.

Is possible to add this intermediate config, isn't ?
Thanks in advance.

**Comment by chrisys** [comment]
@manuti that's awesome, I'm glad it's not running out of tasks now! In our testing we found that any more than 1 task results in this board becomes very unstable and that more progress was made by doing 1 task faster rather than 2 tasks slower. However if you wanted to try it you can deploy the project to your own balena application and adjust the value here to 50 (2 tasks) or 75 (3 tasks): https://github.com/balenalabs/rosetta-at-home/blob/master/boinc-client/start.sh#L34

**Comment by manuti** [comment]
So many thanks @chrisys .
Forked and changed. This evening I'll give a try.

**Comment by manuti** [comment]
Abandoned idea. The 2GB board complete only one task. Constant restart with loose of work done.

**Comment by chrisys** [comment]
@manuti that's what we found, at least you were able to confirm the same thing, and thanks for reporting back!
